#include <gmssl/rsa.h>
#include <gmssl/sha2.h>
#include <gmssl/x509_key.h>

#include <stdio.h>
#include <string.h>

static const char encrypted_rsa_pkcs8_pem[] =
"-----BEGIN ENCRYPTED PRIVATE KEY-----\n"
"MIIFNTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQjxy921J6p6c4wMy3\n"
"UYJtgAICJxAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEJV6PhjlPFBQKqzl\n"
"vOIrS5cEggTQFY6QewxQFAyWiw+rdsO5KfImpkOPYGo9vypiDz1HQl5YWIed7+VD\n"
"7Q5CRVigcTmxN+gMjXTncneNMUSPIFmfQbivE7n5Ts3365YUD2HT9M89tZnvCGRY\n"
"ger2gK2s8MvPUEvfcuW9TfIQf1ikcxMITCHPEXMe32PCqWwHc0XHg4kAq1GH4Pha\n"
"yXvYu7tnksAlmoXgiNusa4vqbiM50w9XBi2pV0KMjUARO0muyKYXPCBT7VTFSpUb\n"
"Qvb+dYac/0QGMAky1glBHJEEdw2B5MObqFQjWmJFALwMj6r4ktqmyOj2R7JcwJp7\n"
"Tfer3X4kbJmkcsyr8EjuoeEf35seBlslAErTElH3UQUpcjZ/FOiwp9bEo/A3EP81\n"
"mGbxq8lfXUw+tuDpHUVK3SEzMCSOKwtOrU1eJnJdnDxkOLaXiWI7FZHDcstOqzcT\n"
"V4B6XupDLxsSr427uvYA4AVqzxcsWL3Llaq7kbc4GkChZSDFVGuFh/6VK617Ncr2\n"
"XY058ABLSUHsKWYh0qBeMCc1lO+d8pBksAdvZG/uZByDDlxVpCjjTgyGa6joQzRn\n"
"tcB2RJi+ThVlMUOkgauJfRMRJD72qIn6AYGhRLW7RE4iu4x3JULX5XyhzTRH4+6C\n"
"w3hbHM9jDILOKI7M3L/BcsHvIzAO/cE07W7995xse5S3idv0ceTfi8s42D7A4Z+Q\n"
"MEGUrISqUOfR2JYQcDv0VQOsFHucrB6G0K+DX3nTPksLi3074wKhhgkA/JiXe023\n"
"0J6lSTiEi3UP++smCSdPAyOzsc4t7oY98+Vpl9C2yC6CDRj6gZbeTiYSXAAyh80t\n"
"RprA+bV7/SnMBTQX+ecS1vab+R377zxe2ZFyBj+CkJmvTMH2wHq6q6G0r2VfX9BR\n"
"Vm5UjD9iysiBSnVcPdVJlqMjMeJVVhofqw+r8Uj/4Wm9S/jrEBZJbUvcfCQe5yUP\n"
"n7KMHqAD0lxRvllbPtXes2LxIX4NzfF4rLzx52g7BbygmBXcsr09YvYh3bjgR7wq\n"
"aJFhs1hrvWoANWXKJhBWr6q7UOFDL4hYlNk8cmyHrhNIEBAeeCTfTKA55dlmxdKK\n"
"ZXQyJy1ex0ag/qo7lLWodKyRKAN3zZTZox7zHK26hREd8OZaN77YRGFqjOD47qtE\n"
"qu3JIHXydybYl5eJ7p8N9OeI6vLg4YP2nOkjvSc2TdzbyBAyXPB2DBt/GjWs7Ug2\n"
"Z3vUrUVQvqJRvIJQTMbqxS5xWOZrTf9I2ZDJzeLJBlovaLOpEj0MV7FGyfYyVfzT\n"
"GrcP39II6kEEqKeEKayIqo8Rfz3+wQOp+y6bkDsgBjsqiI3Vu180fNUIlH0RAMQv\n"
"aESyTjzidh6hMiHJ2Dq8fx9R2njGLPLRWFZSew9xPU83IyDWp71ovR/Ga739p2gI\n"
"hkp4A/AmDY7bc+MTaoMqdiYH+lMNv6meTqdT17nib+NZnNKf01yESuD5qFkqm8/a\n"
"oWjw599RR4W99PiUKbYVCkMo5q31e6KexkPrwU4s0RngqWepf1Zwt7ec7EL+pwVl\n"
"JtiVryHsMTYBhuxPgaQzlN5D6jTsxKrzElJciUkImNrKxtVnlYhUsUnZXAG2vcab\n"
"GbhVoIjsjNxOsGEMPm5OXIKziL/zcU+kH81ixIpFTXXVPxylEJKO/WA=\n"
"-----END ENCRYPTED PRIVATE KEY-----\n";

static int write_fixture(FILE *fp)
{
	if (!fp) return -1;
	if (fputs(encrypted_rsa_pkcs8_pem, fp) == EOF) return -1;
	if (fflush(fp) != 0) return -1;
	rewind(fp);
	return 1;
}

int main(void)
{
	static const uint8_t message[] = "Salts encrypted RSA PKCS8 password contract";
	X509_KEY key;
	X509_KEY wrong_key;
	X509_SIGN_CTX sign_ctx;
	SHA256_CTX sha;
	uint8_t digest[SHA256_DIGEST_SIZE];
	uint8_t signature[RSA_MAX_MODULUS_SIZE];
	size_t signature_len = 0;
	FILE *fp = NULL;
	int rc = 1;

	memset(&key, 0, sizeof(key));
	memset(&wrong_key, 0, sizeof(wrong_key));
	memset(&sign_ctx, 0, sizeof(sign_ctx));
	memset(&sha, 0, sizeof(sha));
	memset(digest, 0, sizeof(digest));
	memset(signature, 0, sizeof(signature));

	/*
	 * Fixture generated by OpenSSL 3.x:
	 *   openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out key.pem
	 *   openssl pkcs8 -topk8 -in key.pem -v2 aes-256-cbc \
	 *     -v2prf hmacWithSHA256 -iter 10000 \
	 *     -passout pass:salts-test-pass -out encrypted.pem
	 */
	fp = tmpfile();
	if (!fp || write_fixture(fp) != 1) return 2;
	if (x509_private_key_from_file(
			&key, OID_rsa_encryption, "salts-test-pass", fp) != 1) {
		rc = 3;
		goto end;
	}
	if (key.algor != OID_rsa_encryption
		|| !key.has_private_key
		|| key.u.rsa_public_key.modulus_size != 256u
		|| key.rsa_private_key.public_key.modulus_size != 256u) {
		rc = 4;
		goto end;
	}

	if (x509_sign_init(&sign_ctx, &key, NULL, 0) != 1
		|| x509_sign_update(&sign_ctx, message, sizeof(message) - 1u) != 1
		|| x509_sign_finish(&sign_ctx, signature, &signature_len) != 1
		|| signature_len != key.u.rsa_public_key.modulus_size) {
		rc = 5;
		goto end;
	}
	sha256_init(&sha);
	sha256_update(&sha, message, sizeof(message) - 1u);
	sha256_finish(&sha, digest);
	if (rsa_verify_pkcs1_v15_sha256(
			&key.u.rsa_public_key, digest, signature, signature_len) != 1) {
		rc = 6;
		goto end;
	}

	fclose(fp);
	fp = tmpfile();
	if (!fp || write_fixture(fp) != 1) {
		rc = 7;
		goto end;
	}
	if (x509_private_key_from_file(
			&wrong_key, OID_rsa_encryption, "wrong-password", fp) == 1) {
		rc = 8;
		goto end;
	}
	if (wrong_key.has_private_key) {
		rc = 9;
		goto end;
	}

	rc = 0;
	puts("GmSSL encrypted RSA PKCS8 key_password contract: PASS");

end:
	if (fp) fclose(fp);
	x509_sign_ctx_cleanup(&sign_ctx);
	x509_key_cleanup(&wrong_key);
	x509_key_cleanup(&key);
	memset(digest, 0, sizeof(digest));
	memset(signature, 0, sizeof(signature));
	return rc;
}
