if(TARGET GmSSL::GmSSL)
    return()
endif()

get_filename_component(_GMSSL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

find_path(_GMSSL_INCLUDE_DIR
    NAMES gmssl/tls.h
    PATHS "${_GMSSL_PREFIX}/include"
    NO_DEFAULT_PATH
    REQUIRED
)

find_library(_GMSSL_RELEASE_LIBRARY
    NAMES gmssl
    PATHS "${_GMSSL_PREFIX}/lib"
    NO_DEFAULT_PATH
    REQUIRED
)

find_library(_GMSSL_DEBUG_LIBRARY
    NAMES gmssl
    PATHS "${_GMSSL_PREFIX}/debug/lib"
    NO_DEFAULT_PATH
)

add_library(GmSSL::GmSSL UNKNOWN IMPORTED)
set_target_properties(GmSSL::GmSSL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_GMSSL_INCLUDE_DIR}"
    INTERFACE_COMPILE_DEFINITIONS "ENABLE_TLS;ENABLE_SECP256R1;ENABLE_SHA2;ENABLE_AES"
    IMPORTED_LOCATION_RELEASE "${_GMSSL_RELEASE_LIBRARY}"
    IMPORTED_LOCATION_RELWITHDEBINFO "${_GMSSL_RELEASE_LIBRARY}"
    IMPORTED_LOCATION_MINSIZEREL "${_GMSSL_RELEASE_LIBRARY}"
)

if(_GMSSL_DEBUG_LIBRARY)
    set_property(TARGET GmSSL::GmSSL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_property(TARGET GmSSL::GmSSL PROPERTY IMPORTED_LOCATION_DEBUG "${_GMSSL_DEBUG_LIBRARY}")
endif()

set_property(TARGET GmSSL::GmSSL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE RELWITHDEBINFO MINSIZEREL)

if(APPLE)
    set_property(TARGET GmSSL::GmSSL APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES "-framework Security")
elseif(WIN32)
    set_property(TARGET GmSSL::GmSSL APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES "Ws2_32")
endif()

unset(_GMSSL_PREFIX)
unset(_GMSSL_INCLUDE_DIR)
unset(_GMSSL_RELEASE_LIBRARY)
unset(_GMSSL_DEBUG_LIBRARY)
